use_frameworks!

platform :ios, '12.0'

target 'FCMediaKit_Example' do
  pod 'FCMediaKit', :path => '../'

  target 'FCMediaKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
